version: '3.8'
services:
  # Base Jenkins Service
  jenkins:
    image: jenkins/jenkins:jdk21
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ${JENKINS_HOME_PATH}:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkinks-net
  # SSH agent for
  ssh-agent:
    image: jenkins/ssh-agent:jdk21
    privileged: true
    user: root
    container_name: ssh-agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}

networks:
  jenkins-net:
    driver: bridge